#!/usr/bin/env python3
"""Step 2 + 3 for unpaired scores: build H/M structure and write annotated TSV.

Uses the abcx->midi files generated by batch_abcx_to_midi_v2.py as the score MIDI
source.  Produces <stem>_structure.json, <stem>_aligned.abcx and
<stem>.annotated_score.mid.tsv next to each .abcx.

Usage:  python3 scripts/step23_unpaired.py --jobs 32
"""
from __future__ import annotations

import csv
import json
import multiprocessing as mp
import sys
from dataclasses import asdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

try:
    from scripts import align_score_performance as asp
except ModuleNotFoundError:
    import align_score_performance as asp

# Reuse annotation parser and merge logic from 03_write_annotated_tsv.py
_03 = Path(__file__).resolve().parent / "03_write_annotated_tsv.py"
_03_code = compile(_03.read_text(), str(_03), "exec")
_03_ns: dict = {}
_03_ns["__file__"] = str(_03)
exec(_03_code, _03_ns)

ABCXAnnotationParser = _03_ns["ABCXAnnotationParser"]
merge_annotations_into_tsv = _03_ns["merge_annotations_into_tsv"]
ABCXHeader = _03_ns["ABCXHeader"]
Annotation = _03_ns["Annotation"]

BASE = Path("/home/sy/EPR/data/unpaired_abcx")

_worker_midi_tsv = None


def _worker_init() -> None:
    global _worker_midi_tsv
    _worker_midi_tsv = asp.load_midi_tsv_module()


def process_one(abcx_path_str: str) -> dict:
    abcx_path = Path(abcx_path_str)
    midi_path = abcx_path.with_suffix(".midi")

    if not midi_path.exists():
        return {"ok": False, "kind": "missing_midi", "name": abcx_path.name}

    try:
        structure = asp.build_score_structure_from_paths(
            midi_path, abcx_path, _worker_midi_tsv, mapping_source=midi_path,
        )
    except Exception as e:
        return {"ok": False, "kind": "structure_error", "name": abcx_path.name,
                "err": str(e)[:200]}

    if structure is None:
        return {"ok": False, "kind": "structure_none", "name": abcx_path.name}

    json_path = abcx_path.parent / f"{abcx_path.stem}_structure.json"
    aligned_path = abcx_path.parent / f"{abcx_path.stem}_aligned.abcx"
    tsv_path = abcx_path.parent / f"{abcx_path.stem}.annotated_score.mid.tsv"

    try:
        # Step 2: write structure JSON + aligned ABCX
        json_path.parent.mkdir(parents=True, exist_ok=True)
        with json_path.open("w", encoding="utf-8") as f:
            json.dump({
                "measures": [asdict(m) for m in structure.measures],
                "phrases": [asdict(p) for p in structure.phrases],
                "measure_to_phrase": structure.measure_to_phrase,
                "abcx_measures": structure.abcx_measures,
                "midi_to_abcx": structure.midi_to_abcx,
                "midi_measure_content": {
                    str(k): v for k, v in sorted(structure.midi_measure_content.items())
                },
            }, f, indent=2, ensure_ascii=False)

        asp.write_aligned_abcx(
            abcx_path, aligned_path, structure.phrases, structure.midi_measure_content,
        )

        # Step 3: generate score MIDI TSV
        tsv_base = midi_path.parent / f"{midi_path.name}.tsv"
        success = asp.generate_score_tsv_with_phrases(
            midi_path, structure, abcx_path, tsv_base, _worker_midi_tsv,
        )
        if not success:
            return {"ok": False, "kind": "tsv_gen_failed", "name": abcx_path.name}

        # Extract annotations from ABCX and merge into TSV
        parser = ABCXAnnotationParser(abcx_path)
        header = parser.extract_header()
        annotations = parser.extract_annotations()

        ok = merge_annotations_into_tsv(
            tsv_base, annotations, header, tsv_path, structure.midi_to_abcx,
        )
        if not ok:
            return {"ok": False, "kind": "merge_failed", "name": abcx_path.name}

        return {"ok": True, "kind": "done", "name": abcx_path.name}

    except Exception as e:
        return {"ok": False, "kind": "exception", "name": abcx_path.name,
                "err": str(e)[:200]}


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--jobs", type=int, default=32)
    args = parser.parse_args()

    abcx_files = sorted(BASE.rglob("abcx/*.abcx"))
    tasks = [str(p) for p in abcx_files if p.with_suffix(".midi").exists()]
    print(f"Found {len(tasks):,} .abcx files with .midi")

    if not tasks:
        print("Nothing to do")
        return

    print(f"Processing with {args.jobs} workers...")
    results: list[dict] = []
    with mp.Pool(args.jobs, initializer=_worker_init) as pool:
        for r in pool.imap_unordered(process_one, tasks):
            results.append(r)
            if len(results) % 500 == 0:
                ok = sum(1 for x in results if x["ok"])
                print(f"  [{len(results)}/{len(tasks)}] ok={ok}")

    ok_count = sum(1 for r in results if r["ok"])
    failed = [r for r in results if not r["ok"]]
    print(f"\nDone: ok={ok_count:,} failed={len(failed):,} total={len(results):,}")

    if failed:
        kinds = {}
        for r in failed:
            k = r["kind"]
            kinds[k] = kinds.get(k, 0) + 1
        print("Failure breakdown:")
        for k, c in sorted(kinds.items(), key=lambda x: -x[1]):
            print(f"  {k}: {c}")
        for r in failed[:10]:
            print(f"  - {r['name']}: {r['kind']} {r.get('err','')}")


if __name__ == "__main__":
    main()
